cli-level = "info"

[lcd]
app-name = "axelar"
host = "localhost"
port = "1317"
keyring-backend = "test"
node = "http://localhost:26657"
chain-id = "axelar"
denom = "axltest"

[lcd.broadcast]
broadcaster-account = "c2d2"
keyring-passphrase = ""
gas-adjustment = "0"
max-retries = 8
min-timeout = 500000000

[db]
data-dir = "./data/db"
enable-logger = false

[bitcoin]
rpc_addr = "http://axelar:Ch91wtRPZhCjKF7OLXkF@bitcoin-node.testnet.axelar.dev:8332"
rpc_user = "axelar"
rpc_pass = "Ch91wtRPZhCjKF7OLXkF"
timeout_rpc = "100s"
zmq-publisher = "tcp://bitcoin-node.testnet.axelar.dev:28332"
network = "test"
confirmation-height = 6
prompt-for-tx = false

[ethereum]
keystore-path = "evm/ethereum"
sender-passphrase = "passwordpassword"
rpc-url = "wss://ropsten.infura.io/ws/v3/2be110f3450b494f8d637ed7bb6954e3"
network = "ropsten"
networkId = 3
confirmation-height = 30
monitor-rpc-url = "wss://ropsten.infura.io/ws/v3/0c3ef74b4cc34cbfade5e1be829fb237"
height-sync-tolerance = 5
